baseURL = 'https://omarjab01.github.io/'
languageCode = 'en-us'
title = 'Omar Jabraoui'
metaDataFormat = "yaml"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Omar Jabraoui"
      introSubtitle = "20 y/o Web Developer & Designer who loves designing and making awesome web apps, crafting beautiful websites and improving user experience."
      introPhoto = "images/mypfp.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Categories"
        url = "tags"
        weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Omar Jabraoui · All rights reserved"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "If you want to get in touch with me or see that i post online, you can find me on these socials"
  linkedin = "https://linkedin.com/in/omarjab"
  github = "https://github.com/omarjab01"
  medium = "https://medium.com/im_omarjab"
[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
